Repository PoweredTable/sist-emprestimo-de-ferramentas, pull requests merged in 2024-06, with the labels that each got.

#82 refactor: refatora os imports com * em EmprestimoDAO
  src/main/java/dao/EmprestimoDAO.java
Labels: refactor

#83 feat: adiciona create database no script do banco
  banco.sql
Labels: enhancement

#85 fix: corrige a dialog de amigo possui emprestimo ativo
  src/main/java/visao/DialogEmprestimo.java
Labels: bug

#86 chore: remove prints do console em DialogEmprestimo
  src/main/java/visao/DialogEmprestimo.java
Labels: invalid

#89 fix: atualiza as tabelas após confirmar ou excluir algum empréstimo
  src/main/java/visao/TelaPrincipal.java
Labels: bug

#97 fix: corrige problema inesplicavel porém auto descritivo
  src/main/java/visao/DialogAmigo.java
  src/main/java/visao/DialogErroConfirmacao.form
  src/main/java/visao/DialogErroConfirmacao.java
  src/main/java/visao/DialogErroTabela.form
  src/main/java/visao/DialogErroTabela.java
  src/main/java/visao/DialogFerramenta.java
  src/main/java/visao/TelaAmigo.java
  src/main/java/visao/TelaFerramenta.java
Labels: invalid

#98 style: Muda o texto de algumas áreas
  src/main/java/visao/TelaPrincipal.java
Labels: refactor

#100 fix: remove métodos redundantes sendo chamados
  src/main/java/visao/TelaAmigo.java
Labels: bug

#101 Fix/amigo ferramenta emprestada
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/FerramentaDAO.java
Labels: bug

#102 fix: resolve problema de dimensionamento
  src/main/java/visao/TelaPrincipal.java
Labels: bug

#104 Chore/coluna data devolucao
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
Labels: enhancement

#106 refactor: refatora o banco para mysql
  banco.sql
  pom.xml
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/DBConexao.java
  src/main/java/dao/FerramentaDAO.java
Labels: bug, refactor

#96 Docs/documentacao padrao
  src/main/java/controle/AmigoControle.java
  src/main/java/controle/EmprestimoControle.java
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/DAO.java
  src/main/java/dao/DBConexao.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/ExceptionDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
  src/main/java/visao/DialogAmigo.java
  src/main/java/visao/DialogEmprestimo.java
  src/main/java/visao/DialogFerramenta.java
  src/main/java/visao/TelaAmigo.form
  src/main/java/visao/TelaAmigo.java
  src/main/java/visao/TelaFerramenta.form
  src/main/java/visao/TelaFerramenta.java
  src/main/java/visao/TelaPrincipal.java
Labels: documentation
