Repository PoweredTable/sist-emprestimo-de-ferramentas, pull requests merged in 2024-05, with the labels that each got.

#2 Merge tela principal para pegar arquivo pom de dependências
  nbactions.xml
  pom.xml
  src/main/java/principal/Principal.java
  src/main/java/visao/Imagens/check.svg
  src/main/java/visao/Imagens/play-pause.svg
  src/main/java/visao/Imagens/trash-xmark.svg
  src/main/java/visao/SVGImage.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
Labels: enhancement

#3 Modelo, DAO's e controladores
  .gitignore
  nbactions.xml
  pom.xml
  queries.sql
  src/main/java/controle/AmigoControle.java
  src/main/java/controle/EmprestimoControle.java
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/DBConnection.java
  src/main/java/dao/Dao.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/ExceptionDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
  src/main/java/principal/Principal.java
  src/main/java/util/TextUtil.java
  src/main/java/visao/Imagens/check.svg
  src/main/java/visao/Imagens/play-pause.svg
  src/main/java/visao/Imagens/trash-xmark.svg
  src/main/java/visao/SVGImage.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
Labels: enhancement

#19 Refatoração e adição de feat no modelo
  banco.sql
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/DAO.java
  src/main/java/dao/DBConexao.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
Labels: enhancement, refactor

#22 Refatora o codigo emprestimo modelo e adiciona algumas features em emprestimoDAO, em modelo ferramenta e amigo
  banco.sql
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
Labels: enhancement, refactor

#24 Correção dos retornos de algumas funções em AmigoDAO e FerramentaDAO
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Ferramenta.java
Labels: bug

#23 Refactors da DAO para JPA
  banco.sql
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
Labels: enhancement, refactor

#26 Corrige as funções buscarNome de amigoDAO e ferramentaDAO e começa a implementação de testes
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/dao/testes/AmigoDAOMain.java
  src/main/java/dao/testes/testeEmprestimoDAO.java
  src/main/java/dao/testes/testeFerramentaDAO.java
Labels: bug, refactor

#27 Revert "Corrige as funções buscarNome de amigoDAO e ferramentaDAO e começa a implementação de testes"
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/dao/testes/AmigoDAOMain.java
  src/main/java/dao/testes/testeEmprestimoDAO.java
  src/main/java/dao/testes/testeFerramentaDAO.java
Labels: bug

#28 Corrige as funções buscarNome de AmigoDAO e FerramentaDAO
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/FerramentaDAO.java
Labels: bug

#29 Adiciona os métodos dos controladores restantes
  src/main/java/controle/AmigoControle.java
  src/main/java/controle/EmprestimoControle.java
  src/main/java/controle/FerramentaControle.java
Labels: enhancement

#30 Correções DAO e controladores
  src/main/java/controle/AmigoControle.java
  src/main/java/controle/EmprestimoControle.java
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/FerramentaDAO.java
Labels: bug, enhancement

#42 Adiciona os métodos de contagem no back-end
  src/main/java/controle/AmigoControle.java
  src/main/java/controle/EmprestimoControle.java
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/DBConexao.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
Labels: enhancement

#45 Corrige os selects das funções de EmprestimoDAO
  src/main/java/dao/EmprestimoDAO.java
Labels: bug

#46 Corrige as funções buscarNome de FerramentaDAO e AmigoDAO
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/FerramentaDAO.java
Labels: bug

#47 Correções DAO e métodos de retorno de quantidade
  src/main/java/controle/AmigoControle.java
  src/main/java/controle/EmprestimoControle.java
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/DBConexao.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
Labels: bug, enhancement, refactor

#49 Tela de amigos e correções back-end
  src/main/java/visao/DialogAmigos.form
  src/main/java/visao/DialogAmigos.java
  src/main/java/visao/TelaAmigos.form
  src/main/java/visao/TelaAmigos.java
  src/main/java/visao/TelaFerramentas.form
  src/main/java/visao/TelaFerramentas.java
  src/main/java/visao/TelaPrincipal.java
Labels: bug, enhancement

#54 feat: adiciona métodos get de datas formatadas de empréstimo
  src/main/java/modelo/Emprestimo.java
Labels: enhancement

#57 fix: deixa somente os create table no banco.sql
  banco.sql
Labels: bug, documentation

#58 fix: corrige os retornos dos selects do DAO
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
Labels: refactor

#60 Tela principal com png
  .gitignore
  pom.xml
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/visao/DialogAmigos.form
  src/main/java/visao/DialogAmigos.java
  src/main/java/visao/DialogFerramentas.form
  src/main/java/visao/DialogFerramentas.java
  src/main/java/visao/Imagens/Em dia.png
  src/main/java/visao/Imagens/add.png
  src/main/java/visao/Imagens/amigos.png
  src/main/java/visao/Imagens/check.png
  src/main/java/visao/Imagens/check.svg
  src/main/java/visao/Imagens/lixeira.png
  src/main/java/visao/Imagens/play-pause.svg
  src/main/java/visao/Imagens/trash.svg
  src/main/java/visao/Imagens/wrench-alt.png
  src/main/java/visao/SVGImage.java
  src/main/java/visao/SVGLabel.java
  src/main/java/visao/TelaAmigos.form
  src/main/java/visao/TelaAmigos.java
  src/main/java/visao/TelaFerramentas.form
  src/main/java/visao/TelaFerramentas.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
Labels: help wanted

#65 Reanimação tela principal, convenções de query e CheckedComboBox
  .gitignore
  banco.sql
  nbactions.xml
  pom.xml
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/visao/DialogAmigo.form
  src/main/java/visao/DialogAmigo.java
  src/main/java/visao/DialogFerramenta.form
  src/main/java/visao/DialogFerramenta.java
  src/main/java/visao/Imagens/check.svg
  src/main/java/visao/Imagens/play-pause.svg
  src/main/java/visao/Imagens/trash.svg
  src/main/java/visao/SVGImage.java
  src/main/java/visao/SVGLabel.java
  src/main/java/visao/TelaAmigo.form
  src/main/java/visao/TelaAmigo.java
  src/main/java/visao/TelaFerramenta.form
  src/main/java/visao/TelaFerramenta.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
Labels: enhancement

#66 fix: corrige o metodo buscar em EmprestimoDAO
  src/main/java/dao/EmprestimoDAO.java
Labels: bug

#67 Feat: dialog emprestimo
  pom.xml
  src/main/java/visao/DialogEmprestimo.form
  src/main/java/visao/DialogEmprestimo.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
  src/main/java/visao/swingcomponents/CheckableModelItem.java
  src/main/java/visao/swingcomponents/CheckedComboBox.java
  src/main/java/visao/swingcomponents/ExemploFerramenta.java
  src/main/java/visao/swingcomponents/ModelItem.java
Labels: enhancement

#68 fix: corrige função buscarFerramentasDisponiveis
  src/main/java/dao/FerramentaDAO.java
Labels: bug

#72 refactor: refatora os construtores dos modelos
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
Labels: refactor

#76 Atualização da branch de documentação
  .gitignore
  banco.sql
  nbactions.xml
  pom.xml
  src/main/java/controle/FerramentaControle.java
  src/main/java/dao/AmigoDAO.java
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
  src/main/java/visao/DialogAmigo.form
  src/main/java/visao/DialogAmigo.java
  src/main/java/visao/DialogConfirmado.form
  src/main/java/visao/DialogConfirmado.java
  src/main/java/visao/DialogEmprestimo.form
  src/main/java/visao/DialogEmprestimo.java
  src/main/java/visao/DialogExclucao.form
  src/main/java/visao/DialogExclucao.java
  src/main/java/visao/DialogFerramenta.form
  src/main/java/visao/DialogFerramenta.java
  src/main/java/visao/Imagens/check.svg
  src/main/java/visao/Imagens/play-pause.svg
  src/main/java/visao/Imagens/trash.svg
  src/main/java/visao/SVGImage.java
  src/main/java/visao/SVGLabel.java
  src/main/java/visao/TelaAmigo.form
  src/main/java/visao/TelaAmigo.java
  src/main/java/visao/TelaFerramenta.form
  src/main/java/visao/TelaFerramenta.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
  src/main/java/visao/swingcomponents/CheckableModelItem.java
  src/main/java/visao/swingcomponents/CheckedComboBox.java
  src/main/java/visao/swingcomponents/ExemploFerramenta.java
  src/main/java/visao/swingcomponents/ModelItem.java
Labels: documentation

#73 Reanimação da tela principal e outros
  pom.xml
  src/main/java/dao/EmprestimoDAO.java
  src/main/java/dao/FerramentaDAO.java
  src/main/java/modelo/Amigo.java
  src/main/java/modelo/Emprestimo.java
  src/main/java/modelo/Ferramenta.java
  src/main/java/visao/DialogConfirmado.form
  src/main/java/visao/DialogConfirmado.java
  src/main/java/visao/DialogEmprestimo.form
  src/main/java/visao/DialogEmprestimo.java
  src/main/java/visao/DialogExclucao.form
  src/main/java/visao/DialogExclucao.java
  src/main/java/visao/TelaAmigo.java
  src/main/java/visao/TelaFerramenta.java
  src/main/java/visao/TelaPrincipal.form
  src/main/java/visao/TelaPrincipal.java
  src/main/java/visao/swingcomponents/CheckableModelItem.java
  src/main/java/visao/swingcomponents/CheckedComboBox.java
  src/main/java/visao/swingcomponents/ExemploFerramenta.java
  src/main/java/visao/swingcomponents/ModelItem.java
Labels: enhancement
